language: python
python:
- '3.6'
branches:
  only: master
deploy:
  provider: lambda
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: travis-lambda-example
env:
  global:
  - secure: AWS_DEFAULT_REGION
  - secure: AWS_ACCESS_KEY_ID
  - secure: AWS_SECRET_ACCESS_KEY
  - secure: AWS_S3_BUCKET
